<?php

/**
 * EiActiveIterationTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiActiveIterationTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiActiveIterationTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiActiveIteration');
    }

    /**
     * @param EiProjet $project
     * @param EiProfil $profile
     *
     * @return EiActiveIteration
     */
    public function getActiveIteration(EiProjet $project = null, EiProfil $profile = null){

        if( $project == null || $profile == null ) return null;
        else return $this->findOneByProjectRefAndProjectIdAndProfileRefAndProfileId(
            $project->getRefId(),
            $project->getProjectId(),
            $profile->getProfileRef(),
            $profile->getProfileId()
        );
    }
}