<?php

/**
 * EiBlockTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiBlockTable extends EiVersionStructureTable {

    /**
     * Returns an instance of this class.
     *
     * @return object EiBlockTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('EiBlock');
    }

    public function getEiBlocksAtLevelQuery($ei_scenario_id, $level) {
        return Doctrine_Query::create()->select('block.*')
                        ->from('EiBlock block, block.EiVersion ver')
                        ->where('block.level = ?', $level)
                        ->andWhere('ver.ei_scenario_id = ?', $ei_scenario_id);
    }

    /**
     * @param $ei_block
     * @return Doctrine_Collection
     *
     * @deprecated
     */
    public function getEiBlockChildrenAccordingToParent($ei_block){
        $query = Doctrine_Query::create()->select('block.*')
                ->from('EiBlock block')
                ->where('block.level = ?', $ei_block->getLevel() + 1)
                ->andWhere('block.ei_version_structure_parent_id = ?', $ei_block->getId())
                ->orderBy('block.lft');
                
        return $query->execute();
    }
    
    public function getEiBlockChildren($ei_block) {
        $query = Doctrine_Query::create()->select('block.*')
                ->from('EiBlock block')
                ->where('block.level = ?', $ei_block->getLevel() + 1)
                ->andWhere('block.ei_version_structure_parent_id = ?', $ei_block->getId());

        return $this->executeGetEiBlockAtQuery($query, $ei_block->getId());
    }

    public function getEiBlockRoot($ei_scenario_id) {
        $res = $this->getEiBlocksAtLevelQuery($ei_scenario_id, 0)
                ->execute();

        if ($res)
            $res = $res->getFirst();

        return $res;
    }

    public function getEiBlockRootId($ei_scenario_id) {
        $query = $this->getEiBlocksAtLevelQuery($ei_scenario_id, 0);
        $query->addSelect('block.id');

        $res = $query->execute();

        if ($res)
            $res = $res->getFirst();

        return $res;
    }

    /**
     * L'identifiant
     * @param type $ei_block_id
     */
    public function getEiBlocks($ei_block_id) {
        $query = self::getInstance()->createQuery('block');

        return $this->executeGetEiBlockAtQuery($query, $ei_block_id);
    }

    private function executeGetEiBlockAtQuery($query, $ei_block_id) {
        $treeObj = self::getInstance()->getTree();
        $treeObj->setBaseQuery($query);
        $tree = $treeObj->fetchTree(array('root_id' => $ei_block_id));

        $treeObj->resetBaseQuery();

        return $tree;
    }

    /**
     * Retourne la liste des paramètres d'un block.
     *
     * @param $ei_block_id
     * @return mixed
     */
    public function getEiBlocksParams($ei_block_id) {
        $ei_params = Doctrine_Query::create()
            ->select('bp.*')
            ->from('EiBlockParam bp')
            ->where('bp.ei_version_structure_parent_id = '.$ei_block_id)
            ->orderBy('bp.lft')
            ->execute();
        ;

        return $ei_params;

    }

    public function getEiBlocksWithParams($ei_block_id, array $types = array()) {
        return Doctrine_Core::getTable("EiVersionStructure")
            ->getEiBlocksWithParams($ei_block_id, array(
                EiVersionStructure::$TYPE_BLOCK
            ))
        ;
    }

}