<?php

/**
 * EiBlockParamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiBlockParamTable extends EiVersionStructureTable
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiBlockParamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiBlockParam');
    }

    /**
     * @param $rootId
     * @param $level
     * @return Doctrine_Collection
     */
    public function getAllAscendantsParams($rootId, $level){
        return $this->createQuery('p')
            ->where('p.root_id = ? ', $rootId)
            ->andWhere('p.level <= ?', $level + 1)
            ->orderBy('p.lft')
            ->execute();
    }

    /**
     * @param $structure_parent_id
     * @param $level
     * @return Doctrine_Query
     */
    public function getQueryToFindBlockParams($structure_parent_id, $level)
    {
        /** @var Doctrine_Query $query */
        $query = $this->createQuery("p")
            ->where("p.ei_version_structure_parent_id = ?", $structure_parent_id)
            ->andWhere("p.level = ?", $level + 1)
            ->orderBy("p.lft")
        ;

        return $query;
    }
}