<?php

/**
 * EiBlockDataSetMappingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiBlockDataSetMappingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiBlockDataSetMappingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiBlockDataSetMapping');
    }
}