<?php

/**
 * EiDeviceTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiDeviceTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiDeviceTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiDeviceType');
    }
}