<?php

/**
 * EiDeviceUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiDeviceUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiDeviceUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiDeviceUser');
    }
    
    public static function getMyDevices($user_id)
    {
        $conn = Doctrine_Manager::connection();
        $result = $conn->fetchAll("select du.id, d.id as device_id, du.name as device_name, duv.name as visibility, sgu.username, d.device_identifier, dt.name, dt.logo_path "
                . "from ei_device_user du "
                . "inner join ei_device_user_visibility duv on du.device_user_visibility_id = duv.id "
                . "inner join sf_guard_user sgu on du.owner = sgu.id "
                . "inner join ei_device d on du.device_id = d.id "
                . "inner join ei_device_type dt on d.device_type_id = dt.id "
                . "where du.device_user_visibility_id = '1' or (du.device_user_visibility_id = '2' and du.owner = '" . $user_id . "');");
        return $result;
    }
    
    public static function getMyDevicesId($user_id)
    {
        $conn = Doctrine_Manager::connection();
        $result = $conn->fetchAll("select du.id, du.device_id "
                . "from ei_device_user du "
                . "where du.device_user_visibility_id = '1' or (du.device_user_visibility_id = '2' and du.owner = '" . $user_id . "');");
        return $result;
    }
}