<?php

/**
 * EiDriverTypeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiDriverTypeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiDriverTypeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiDriverType');
    }
}