<?php

/**
 * EiExcelRequestsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiExcelRequestsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiExcelRequestsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiExcelRequests');
    }

    /**
     * @param $user_ref
     * @param $user_id
     */
    public function getLastUserRequest($user_ref, $user_id)
    {
        return $this->createQuery("e")
            ->andWhere("e.state = 0")
            ->andWhere("e.user_ref = ? AND e.user_id = ?", array($user_ref, $user_id))
            ->orderBy("e.id DESC")
            ->fetchOne()
            ;
    }
}