<?php

/**
 * EiExcelRequests
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kalifastRobot
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EiExcelRequests extends BaseEiExcelRequests
{
    /** @var EiProfil $profil */
    private $profil = null;

    /** @var EiDataSet|EiTestSet $payload */
    private $payload = null;

    /** @var EiScenario $scenario */
    private $scenario = null;

    /**
     * @return EiProfil
     */
    public function getProfil()
    {
        if( $this->profil == null){
            $this->profil = Doctrine_Core::getTable("EiProfil")->findOneByProfileRefAndProfileId(
                $this->getProfileRef(),
                $this->getProfileId()
            );

            $this->profil = $this->profil == false ? null:$this->profil;
        }

        return $this->profil;
    }

    /**
     * @return EiDataSet|EiTestSet
     */
    public function getPayload()
    {

    }

    /**
     *
     */
    public function getScenario()
    {
        if( $this->scenario == null )
        {
            /** @var EiDataSetTable $tableDataSet */
            $tableDataSet = EiDataSetTable::getInstance();

            if( $this->getEiTestSet() != null && $this->getEiTestSetId() != "" ){
                $this->scenario = $this->getEiTestSet()->getEiScenario();
            }
            elseif( $this->getEiDataSet() != null && $this->getEiDataSetId() != "" ){
                $this->scenario = $tableDataSet->getDataSetScenario($this->getEiDataSet());
            }
        }

        return $this->scenario;
    }

    public function save(Doctrine_Connection $conn = null)
    {
        if( $this->getEiDataSetId() != "" ){
            $this->setEiDataSetTemplate($this->getEiDataSet()->getEiDataSetTemplate());
        }
        parent::save($conn);
    }
}