<?php

/**
 * EiFlagTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiFlagTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiFlagTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiFlag');
    }
}