<?php

/**
 * EiFlagScenarioTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiFlagScenarioTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiFlagScenarioTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiFlagScenario');
    }
}