<?php

/**
 * EiFlagFunctionTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiFlagFunctionTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiFlagFunctionTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiFlagFunction');
    }
}