<?php

/**
 * EiFolderTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiFolderTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiFolderTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiFolder');
    }
    
    
    public function rename($obj_id,$new_node_name,$conn){
        if($new_node_name=="" || $obj_id==null) return null;
        if($conn==null) $conn = Doctrine_Manager::connection(); 
        $ei_folder=$this->getInstance()->findOneById($obj_id);
        if($ei_folder!=null) {
            $ei_folder->setName($new_node_name);
            $ei_folder->save($conn);
        }
    }
}