<?php

/**
 * EifunctionCampaignsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EifunctionCampaignsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EifunctionCampaignsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EifunctionCampaigns');
    }
}