<?php

/**
 * EiLogFunctionSeleniumTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiLogFunctionSeleniumTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiLogFunctionSeleniumTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiLogFunctionSelenium');
    }
}