<?php

/**
 * EiParamBlockFunctionMappingTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiParamBlockFunctionMappingTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiParamBlockFunctionMappingTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiParamBlockFunctionMapping');
    }
}