<?php

/**
 * EiPackageScenarioConflictHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiPackageScenarioConflictHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiPackageScenarioConflictHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiPackageScenarioConflictHistory');
    }
}