<?php

/**
 * EiProjectLangTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiProjectLangTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiProjectLangTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiProjectLang');
    }
    
    //Rechargement des éléments de type EiProjectLang pour un projet 
    public function reload($projets,$project_id, $project_ref, Doctrine_Connection $conn = null) {
        if ($conn == null)
            $conn = Doctrine_Manager::connection();

        //Création de la collection d'objet EiProjectLang à ajouter
        $collection = new Doctrine_Collection("EiProjectLang");
        
        $items = $projets->getElementsByTagName("ei_project_langs");
        if ($items->length > 0) {//ya t-il des éléments à traiter?
            $ei_project_langs = $items->item(0)->getElementsByTagName("ei_project_lang");


            if($ei_project_langs->length > 0){
                foreach ($ei_project_langs as $ei_project_lang) {

                    $lang_id = $ei_project_lang->getAttribute("lang"); 
                    //recherche du profil en base
                    if ($lang_id != null && $project_ref!=null && $project_id!=null) { 
                        $new_ei_project_lang = new EiProjectLang();
                        $new_ei_project_lang->setLang($lang_id);
                        $new_ei_project_lang->setProjectId($project_id);
                        $new_ei_project_lang->setProjectRef($project_ref); 
                        $collection->add($new_ei_project_lang);
                    }
                }
                if($collection->getFirst()) $collection->save($conn); //Sauvegarde de la collection
                return 1;
            }
            return null;
        }
    }
    
    /* Suppression des langues d'un projet donné   */
    public function deleteProjectLangs($project_id, $project_ref ,  Doctrine_Connection $conn = null){ 
        if ($conn == null)  $conn = Doctrine_Manager::connection();
            $conn->getTable('EiProjectLang')->createQuery('pl')
                ->delete()
                ->where('pl.project_id=? And pl.project_ref=?',
                        array($project_id,$project_ref)) 
                ->execute(); 
    }
}