<?php

/**
 * EiProfileParamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiProfileParamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiProfileParamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiProfileParam');
    }
    //Rechargement des éléments de type EiProfileParam pour un projet 
    public function reload($projets,$project_id, $project_ref, Doctrine_Connection $conn = null) {
        if ($conn == null)
            $conn = Doctrine_Manager::connection();

        $items = $projets->getElementsByTagName("ei_profile_params");
        if ($items->length > 0) {//ya t-il des éléments à traiter?
            $ei_profile_params = $items->item(0)->getElementsByTagName("ei_profile_param");
            $stmt = $conn->prepare("INSERT INTO ei_profile_param (id, profile_id, profile_ref,name,description,value) "
                            ."VALUES (:id, :profile_id, :profile_ref,:name,:description,:value) "
                            ."ON DUPLICATE KEY UPDATE id=id  ");
            
            if ($ei_profile_params->length > 0) {
                foreach ($ei_profile_params as $ei_profile_param) {

                    $id = $ei_profile_param->getAttribute("id");
                    //recherche du profil en base
                    if ($id != null) { 
                        $stmt->bindValue("id", $id);
                        $stmt->bindValue("profile_id", $ei_profile_param->getElementsByTagName("profile_id")->item(0)->nodeValue);
                        $stmt->bindValue("profile_ref", $ei_profile_param->getElementsByTagName("profile_ref")->item(0)->nodeValue);
                        $stmt->bindValue("name", $ei_profile_param->getElementsByTagName("name")->item(0)->nodeValue);
                        $stmt->bindValue("description", $ei_profile_param->getElementsByTagName("description")->item(0)->nodeValue);  
                        $stmt->bindValue("value", $ei_profile_param->getElementsByTagName("value")->item(0)->nodeValue);  
                        $stmt->execute(array());    
                    }
                } 
                return 1;
            }
            return null;
        }
    }
    
    /* Suppression des paramètres de profil pour un projet donné */
    public function deleteProjectProfileParams($project_id, $project_ref ,  Doctrine_Connection $conn = null){ 
        if ($conn == null)  $conn = Doctrine_Manager::connection(); 
            $q="DELETE FROM `ei_profile_param`  
                where (profile_id,profile_ref) in 
                ( select 
                    p.profile_id, p.profile_ref from  ei_profil p  
                where p.project_id=".$project_id." and p.project_ref=".$project_ref.")";
                   $conn->execute($q) ; 
    }
    
}