<?php

/**
 * EiScenarioExecutableTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiScenarioExecutableTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiScenarioExecutableTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiScenarioExecutable');
    }
}