<?php

/**
 * EiScriptVersion
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kalifastRobot
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EiScriptVersion extends BaseEiScriptVersion
{
//    public function setUp() {
//        parent::setUp();
//        $this->hasMany('EiScript as scriptsLink', array(
//             'local' => Array('ref_script','id_script'), 
//             'foreign' => Array('ref_script','id_script'))) ;
//    
//    }
}
