<?php

/**
 * EiSubjectHasApplicationObjectTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiSubjectHasApplicationObjectTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiSubjectHasApplicationObjectTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiSubjectHasApplicationObject');
    }
}