<?php

/**
 * EiSubjectCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiSubjectCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiSubjectCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiSubjectCategory');
    }
}