<?php

/**
 * EiSubjectHasCategoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiSubjectHasCategoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiSubjectHasCategoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiSubjectHasCategory');
    }
}