<?php

/**
 * EiSubjectPriorityHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiSubjectPriorityHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiSubjectPriorityHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiSubjectPriorityHistory');
    }
}