<?php

/**
 * EiSubjectHasTaskTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiSubjectHasTaskTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiSubjectHasTaskTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiSubjectHasTask');
    }
}