<?php

/**
 * EiSubjectAssignment
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kalifastRobot
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EiSubjectAssignment extends BaseEiSubjectAssignment {

    public function save(\Doctrine_Connection $conn = null) {

        if ($conn == null)
            $conn = Doctrine_Manager::connection();

        try {
            $conn->beginTransaction();
            if ($this->isNew()): //On crée l'historique d'assignation du bug 
                $ret = parent::save($conn);
                Doctrine_Core::getTable('EiSubjectAssignmentHistory')->createAssignmentHistory(
                $this,true,$conn); 
            else:
                $ret = parent::save($conn);
            endif;
            $conn->commit();
            return $ret;
        } catch (Exception $e) {
            $conn->rollback();
            throw $e;
        }
    }

    public function delete(\Doctrine_Connection $conn = null) {

        if ($conn == null)
            $conn = Doctrine_Manager::connection();

        try {
            $conn->beginTransaction();
            Doctrine_Core::getTable('EiSubjectAssignmentHistory')->createAssignmentHistory($this,false,$conn);  
            $ret = parent::delete($conn);
            $conn->commit();
            return $ret;
        } catch (Exception $e) {
            $conn->rollback();
            throw $e;
        }
    }

}
