<?php

/**
 * EiSubjectAssignmentHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiSubjectAssignmentHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiSubjectAssignmentHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiSubjectAssignmentHistory');
    }
    //Création d'une historique  d'assignation 
    public function createAssignmentHistory(EiSubjectAssignment $assignment,$is_assignment=true,Doctrine_Connection $conn = null){
        if ($conn == null)
            $conn = Doctrine_Manager::connection();  
        
        return $conn->insert($this->getInstance(), array(
            'author_of_assignment' => MyFunction::getGuard()->getId(),
            'subject_id' => $assignment->getSubjectId(),
            'assign_to' => $assignment->getGuardId(),
            'date' => date("Y-m-d H:i:s"),
            'is_assignment' => $is_assignment));
    }
    /* Récupération des assignations */
    public function getAssignmentsHistory($subject_id=null,Doctrine_Connection $conn=null){
        
        $q="SELECT sa_vw.* FROM  ei_subject_assignment_vw as sa_vw   "; 
        if($subject_id!=null) $q.="  WHERE  sah_subject_id=".$subject_id; 
        $q.= ' Order by  sah_date DESC Limit 20';
         return $conn->fetchAll($q);
    }
}