<?php

/**
 * EiTaskAssignmentTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiTaskAssignmentTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiTaskAssignmentTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiTaskAssignment');
    }
}