<?php

/**
 * EiTaskAuthorHistoryTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiTaskAuthorHistoryTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiTaskAuthorHistoryTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiTaskAuthorHistory');
    }
}