<?php

/**
 * EiTaskStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiTaskStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiTaskStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiTaskState');
    }
}