<?php

/**
 * EiTestSetParamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiTestSetParamTable extends Doctrine_Table {

    /**
     * Returns an instance of this class.
     *
     * @return object EiTestSetParamTable
     */
    public static function getInstance() {
        return Doctrine_Core::getTable('EiTestSetParam');
    }

    /* Récupération de tous les paramètres interprétés d'un jeu de test.
     * Ces paramètres serviront surtout à interpréter des paramètres variables d
     * de version de notice 
     */

    public function getTestSetParam(EiTestSet $ei_test_set) {

        $conn = Doctrine_Manager::connection();
        $q = "
         
         SELECT p.*, f.* , fp.name

         FROM  ei_test_set_param p
        LEFT   JOIN ei_test_set_function f
             ON f.id = p.ei_test_set_function_id
             AND f.ei_test_set_id =p.ei_test_set_id
        
        LEFT   JOIN ei_function_has_param fp
             ON fp.param_id = p.param_id
        
        WHERE p.ei_test_set_id= " . $ei_test_set->getId() . "
        
        ORDER BY f.position     
        ";
        return $conn->fetchAll($q);
    }

    /* Récupération des paramètres d'une EiFonction pour un jeu de test */

    public function getParamForTestSetAndEiFonction($ei_test_set_id, $ei_fonction_id) {
        if ($ei_fonction_id == null || $ei_test_set_id == null)
            return array();
        $conn = Doctrine_Manager::connection();

        $q = " 
                        SELECT p.*, f.* , fp.name

                        FROM  ei_test_set_param p
                       LEFT   JOIN ei_test_set_function f
                            ON f.id = p.ei_test_set_function_id
                            AND f.ei_test_set_id =p.ei_test_set_id

                       LEFT   JOIN ei_function_has_param fp
                            ON fp.param_id = p.param_id

                       WHERE p.ei_test_set_id= " . $ei_test_set_id . "
                       AND f.ei_fonction_id= " . $ei_fonction_id. "    

                       ORDER BY f.position     
                       ";
        
        return $conn->fetchAll($q);
    }

    /* Récupération des paramètres d'une EiTestSetFunction pour un jeu de test */

    public function getParamForTestSetAndEiTestFunction($ei_test_set_id, $ei_fonction_id) {
        if ($ei_fonction_id == null || $ei_test_set_id == null)
            return array();
        $conn = Doctrine_Manager::connection();

        $q = "
                        SELECT p.*, f.* , fp.name

                        FROM  ei_test_set_param p
                       LEFT   JOIN ei_test_set_function f
                            ON f.id = p.ei_test_set_function_id
                            AND f.ei_test_set_id =p.ei_test_set_id

                       LEFT   JOIN ei_function_has_param fp
                            ON fp.param_id = p.param_id

                       WHERE p.ei_test_set_id= " . $ei_test_set_id . "
                       AND p.ei_test_set_function_id= " . $ei_fonction_id. "

                       ORDER BY f.position
                       ";

        return $conn->fetchAll($q);
    }
    
    /* Récupération des paramètres de sortie d'une fonction pour un jeu de test */

    public function getParamForLogAndEiFonction($ei_test_set_id, $ei_fonction_id) {
        if ($ei_fonction_id == null || $ei_test_set_id == null)
            return array();
        $conn = Doctrine_Manager::connection();

        $q = " 
                        SELECT fp.* , lf.* , lp.*

                        FROM  ei_log_param lp
                       LEFT   JOIN ei_log_function lf
                            ON lp.ei_log_function_id = lf.id
                            AND lp.ei_test_set_id =lf.ei_test_set_id

                       LEFT   JOIN ei_function_has_param fp
                            ON lp.ei_param_id = fp.param_id

                       WHERE lp.ei_test_set_id= " . $ei_test_set_id . "
                       AND lf.ei_fonction_id= " . $ei_fonction_id. "    
                       AND lp.param_type = 'OUT' 
                       ";
        
        return $conn->fetchAll($q);
    }

    /* Récupération des paramètres de sortie d'une fonction pour un jeu de test */

    public function getParamForLogAndEiTestSetFunction($ei_test_set_id, $ei_fonction_id) {
        if ($ei_fonction_id == null || $ei_test_set_id == null)
            return array();
        $conn = Doctrine_Manager::connection();

        $q = "
                        SELECT fp.* , lf.* , lp.*

                        FROM  ei_log_param lp
                       LEFT   JOIN ei_log_function lf
                            ON lp.ei_log_function_id = lf.id
                            AND lp.ei_test_set_id =lf.ei_test_set_id

                       LEFT   JOIN ei_function_has_param fp
                            ON lp.ei_param_id = fp.param_id

                       WHERE lp.ei_test_set_id= " . $ei_test_set_id . "
                       AND lf.ei_test_set_function_id= " . $ei_fonction_id. "
                       AND lp.param_type = 'OUT'
                       ";

        return $conn->fetchAll($q);
    }

}