<?php

/**
 * EiTestSetStateTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiTestSetStateTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiTestSetStateTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiTestSetState');
    }
}