<?php

/**
 * EiUserProfileParamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiUserProfileParamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiUserProfileParamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiUserProfileParam');
    }
}