<?php

/**
 * EiUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kalifastRobot
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class EiUser extends BaseEiUser
{
     public function __toString() {

        return sprintf('%s', $this->getGuardUser());
    }

    public function getGuardUser(){
       return  Doctrine_Core::getTable('sfGuardUser')->findOneById($this->getGuardId());
    }
    
    /* Récupérer le profil utilisateur par défaut sur un projet */
    public function getDefaultProfile(EiProjet $ei_project , Doctrine_Connection $conn = null){
        if($conn==null) $conn = Doctrine_Manager::connection(); 
        return $this->getTable()->getDefaultProfile($this->getUserId(),$this->getRefId(),$ei_project->getProjectId(),$ei_project->getRefId(),$conn);
    }
    /* Récupération de l'intervention par défaut pour un utilisateur */
    public function getDefaultIntervention( EiProjet $ei_project , Doctrine_Connection $conn = null){
        if($conn==null) $conn = Doctrine_Manager::connection();  
        return $conn->fetchRow("select s.id as subject_id,s.name as subject_name, s.package_id,s.package_ref ,t.name as ticket_name  from ei_subject s ". 
                                 " inner join ei_ticket t on s.package_id=t.ticket_id and s.package_ref=t.ticket_ref ".
                                " inner join ei_user_default_package udp on t.ticket_id=udp.ticket_id and t.ticket_ref=udp.ticket_ref ".
                                " where udp.user_id=".$this->getUserId()." and udp.user_ref=".$this->getRefId().
                                " and s.project_id=".$ei_project->getProjectId()." and s.project_ref=".$ei_project->getRefId()); 
    }
    /* Récupération de l'intervention par défaut d'un utilisateur avec la liaison sur une version du  scénario */
    public function getDefaultInterventionWithScenarioVersion( EiProjet $ei_project ,EiVersion $ei_version, Doctrine_Connection $conn = null){
        if($conn==null) $conn = Doctrine_Manager::connection();  
        return $conn->fetchRow("select s.id as subject_id,s.name as subject_name,sp.ei_version_id as sp_ei_version_id, s.package_id,s.package_ref ,t.name as ticket_name  from ei_subject s ". 
                                 " inner join ei_ticket t on s.package_id=t.ticket_id and s.package_ref=t.ticket_ref ".
                                 " Left join ei_scenario_package sp on sp.package_id=t.ticket_id and sp.package_ref=t.ticket_ref and sp.ei_scenario_id=".
                                 $ei_version->getEiScenarioId().
                                " inner join ei_user_default_package udp on t.ticket_id=udp.ticket_id and t.ticket_ref=udp.ticket_ref ".
                                " where udp.user_id=".$this->getUserId()." and udp.user_ref=".$this->getRefId().
                                " and s.project_id=".$ei_project->getProjectId()." and s.project_ref=".$ei_project->getRefId());
    }
}
