<?php

/**
 * EiUserSettingsTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class EiUserSettingsTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object EiUserSettingsTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('EiUserSettings');
    }
}