<?php

/**
 * ScriptEiProjetTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScriptEiProjetTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScriptEiProjetTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScriptEiProjet');
    }
}