<?php

/**
 * ScriptEiUserTicketTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScriptEiUserTicketTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScriptEiUserTicketTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScriptEiUserTicket');
    }
}