<?php

/**
 * ScriptEiNoticeProfilTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScriptEiNoticeProfilTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScriptEiNoticeProfilTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScriptEiNoticeProfil');
    }
    
    public function insertTmpData($projets,$project_id, $project_ref, Doctrine_Connection $conn = null) {
        if ($conn == null)
            $conn = Doctrine_Manager::connection();
        //On vide la table temporaire avant toute opération  
        $conn->execute("TRUNCATE TABLE script_ei_notice_profil");

        $items = $projets->getElementsByTagName("ei_notice_profiles");
        if ($items->length !=0) {//ya t-il des éléments à traiter?
            $ei_notice_profiles = $items->item(0)->getElementsByTagName("ei_notice_profile");
            $stmt = $conn->prepare("INSERT INTO script_ei_notice_profil (notice_id, notice_ref, profile_id,profile_ref,version_notice_id) "
                            ."VALUES (:notice_id, :notice_ref, :profile_id,:profile_ref,:version_notice_id) "
                            ."ON DUPLICATE KEY UPDATE notice_id=notice_id,notice_ref=notice_ref  ");

            if($ei_notice_profiles->length !=0){
            foreach ($ei_notice_profiles as $ei_notice_profile) {

                $notice_id = $ei_notice_profile->getAttribute("notice_id");
                $notice_ref = $ei_notice_profile->getAttribute("notice_ref");
                $profile_id = $ei_notice_profile->getAttribute("profile_id");
                $profile_ref = $ei_notice_profile->getAttribute("profile_ref");
                $version_notice_id = $ei_notice_profile->getAttribute("version_notice_id");
                //recherche du profil en base
                if ($notice_id != null && $notice_ref != null && $version_notice_id != null
                        && $profile_id != null && $profile_ref != null) { 
                    $stmt->bindValue("notice_id", $notice_id);
                        $stmt->bindValue("notice_ref", $notice_ref);
                        $stmt->bindValue("profile_id", $profile_id);
                        $stmt->bindValue("profile_ref", $profile_ref);  
                        $stmt->bindValue("version_notice_id",$version_notice_id);  
                        $stmt->execute(array()); 
                }
            }  
            }
        }
        return null;
    }
}