<?php

/**
 * ScriptEiProjectParamTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScriptEiProjectParamTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScriptEiProjectParamTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScriptEiProjectParam');
    }
}