<?php

/**
 * ScriptEiProjectUserTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScriptEiProjectUserTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScriptEiProjectUserTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScriptEiProjectUser');
    }
}