<?php

/**
 * ScriptEiFunctionHasCommandeTable
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class ScriptEiFunctionHasCommandeTable extends Doctrine_Table
{
    /**
     * Returns an instance of this class.
     *
     * @return object ScriptEiFunctionHasCommandeTable
     */
    public static function getInstance()
    {
        return Doctrine_Core::getTable('ScriptEiFunctionHasCommande');
    }
    
    //Avec l'objet conn pour pouvoir intégrer la fonction à une transaction
    //Réchargement des données ScriptEiFunctionHasCommande
    
    public function ReloadInterfaceCommandes($id_kal_fonction, $ref_kal_fonction,$eicommandesBalise,Doctrine_Connection $conn =null){
         if($conn==null) $conn = Doctrine_Manager::connection();
        $eicommandes = $eicommandesBalise->getElementsByTagName("ei_commande");
        if ($eicommandes->length !=0) { //s'il ya au moins une balise ei_commande trouvé
         
            
                    
            foreach ($eicommandes as $eicommande) {
                //On procède par du delete-insert car plus rapide que la requete de mise à jour
                //On vérifie qu'on a bien récupérer les clés primaires de la table car éléments primordials pour bien executer les requetes
                if (($ref_function = $eicommande->getElementsByTagName("ref_function")->item(0)->nodeValue) &&
                        ($id_function = $eicommande->getElementsByTagName("id_function")->item(0)->nodeValue) &&
                        ($id_script = $eicommande->getElementsByTagName("id_script")->item(0)->nodeValue) &&
                        ($version_script = $eicommande->getElementsByTagName("version_script")->item(0)->nodeValue) &&
                        ($ordre = $eicommande->getElementsByTagName("ordre")->item(0)->nodeValue) && $conn != null) {
                    
                    //Reinsertion de l'objet
                    $conn->insert($conn->getTable('ScriptEiFunctionHasCommande'), array('ref_function' => $ref_function,
                        'id_function' => $id_function,
                        'id_script' => $id_script,
                        'version_script' => $version_script,
                        'ordre' => $ordre,
                        'ref_selenium' => $eicommande->getElementsByTagName("ref_selenium")->item(0)->nodeValue,
                        'nom_commande' => $eicommande->getElementsByTagName("nom_commande")->item(0)->nodeValue,
                        'cible_commande' => $eicommande->getElementsByTagName("cible_commande")->item(0)->nodeValue,
                        'valeur_commande' => $eicommande->getElementsByTagName("valeur_commande")->item(0)->nodeValue,
                        'created_at' => $eicommande->getElementsByTagName("created_at")->item(0)->nodeValue,
                        'updated_at' => $eicommande->getElementsByTagName("updated_at")->item(0)->nodeValue));
                }
            }
        }
    }        
}