<?php

/**
 * sfGuardUser
 * 
 * This class has been auto-generated by the Doctrine ORM Framework
 * 
 * @package    kalifast
 * @subpackage model
 * @author     Your name here
 * @version    SVN: $Id: Builder.php 7490 2010-03-29 19:53:27Z jwage $
 */
class sfGuardUser extends PluginsfGuardUser
{
    public function setUp() {
        parent::setUp();
        $this->hasMany('EiSubjectAssignment as userAssignmentsSubjects', array(
             'local' => 'id',
             'foreign' => 'guard_id'));
    }
     
    public function getProjetsQuery(){
         return Doctrine_Core::getTable('EiProjet')
                ->createQuery('p')
                ->where('EiProjectUser.project_id=p.project_id And EiProjectUser.project_ref=p.ref_id ')
                ->AndWhere('EiUser.user_id=EiProjectUser.user_id And EiUser.ref_id=EiProjectUser.user_ref ')
                ->where('EiUser.guard_id=? And p.obsolete = false', $this->getId());
    } 
    public function getOrderProjetsQueryByDate(){
         return $this->getProjetsQuery()
                 ->orderBy(' p.created_at,p.updated_at,p.checked_at Asc');
    }

    /**
     * @return EiUser
     */
    public function getEiUser(){
        return Doctrine_Core::getTable('EiUser')->findOneByGuardId($this->getId());
    }
    
}
