<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version1 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->createTable('ei_browser_type', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'hidden_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'logo_path' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('ei_device', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'device_identifier' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'device_type_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('ei_device_driver', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'device_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'driver_type_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('ei_device_type', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'hidden_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'logo_path' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('ei_device_user', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'device_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'owner' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'device_user_visibility_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('ei_device_user_visibility', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('ei_driver_browser', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'device_driver_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'browser_type_id' => 
             array(
              'type' => 'integer',
              'notnull' => '1',
              'length' => '8',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->createTable('ei_driver_type', array(
             'id' => 
             array(
              'type' => 'integer',
              'length' => '8',
              'autoincrement' => '1',
              'primary' => '1',
             ),
             'name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'hidden_name' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'logo_path' => 
             array(
              'type' => 'string',
              'notnull' => '1',
              'length' => '255',
             ),
             'created_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             'updated_at' => 
             array(
              'notnull' => '1',
              'type' => 'timestamp',
              'length' => '25',
             ),
             ), array(
             'type' => 'InnoDB',
             'primary' => 
             array(
              0 => 'id',
             ),
             'collate' => 'utf8_general_ci',
             'charset' => 'utf8',
             ));
        $this->addColumn('ei_execution_stack', 'device_id', 'integer', '8', array(
             'notnull' => '',
             ));
        $this->addColumn('ei_execution_stack', 'driver_id', 'integer', '8', array(
             'notnull' => '',
             ));
        $this->addColumn('ei_execution_stack', 'browser_id', 'integer', '8', array(
             'notnull' => '',
             ));
    }
	
	public function postUp() {
		$conn=Doctrine_Manager::getInstance()->getCurrentConnection();
		$stmt=$conn->prepare('INSERT INTO ei_device_user_visibility (`name`) VALUES (:name)');
		foreach(array(array('name'=>'Public'), array('name'=> 'Private')) as $v) {
			$stmt->execute($v);
		}

		$stmt=$conn->prepare('INSERT INTO ei_device_type (`name`, `hidden_name`, `logo_path`) VALUES (:name, :hidden_name, :logo_path)');
		foreach(	array(array('name'=>'Klikbox', 'hidden_name'=>'klikbox', 'logo_path'=>'app_icone_raspberry_24x24_path'),
					array('name'=>'Windows', 'hidden_name'=>'windows', 'logo_path'=>'app_icone_windows_24x24_path'),
					array('name'=>'Mac', 'hidden_name'=>'mac', 'logo_path'=>'app_icone_apple_16x16_path'),
					array('name'=>'iOS', 'hidden_name'=>'ios', 'logo_path'=>'app_icone_apple_16x16_path'),
					array('name'=>'Android', 'hidden_name'=>'android', 'logo_path'=>'app_icone_android_16x16_path'),
					array('name'=>'Linux', 'hidden_name'=>'linux', 'logo_path'=>'app_icone_linux_24x24_path')) as $v) {
			$stmt->execute($v);
		}

		$stmt=$conn->prepare('INSERT INTO ei_driver_type (`name`, `hidden_name`, `logo_path`) VALUES (:name, :hidden_name, :logo_path)');
		foreach(array(	array('name'=>'Selenium IDE', 'hidden_name'=>'selenium_ide', 'logo_path'=>'app_icone_selenium_24x24_path'),
						array('name'=>'Kalifast Webdriver', 'hidden_name'=>'kalifast_webdriver', 'logo_path'=>'app_logo_kalifast_webdriver')) as $v) {
			$stmt->execute($v);
		}

		$stmt=$conn->prepare('INSERT INTO ei_browser_type (`name`, `hidden_name`, `logo_path`) VALUES (:name, :hidden_name, :logo_path)');
		foreach(array(	array('name'=>'Chrome', 'hidden_name'=>'chrome', 'logo_path'=>'app_icone_chrome_24x24_path'),
						array('name'=>'Firefox', 'hidden_name'=>'firefox', 'logo_path'=>'app_icone_firefox_24x24_path'),
						array('name'=>'Internet Explorer', 'hidden_name'=>'internet_explorer', 'logo_path'=>'app_icone_ie_2_24x24_path'),
						array('name'=>'Edge', 'hidden_name'=>'edge', 'logo_path'=>'app_icone_edge_24x24_path'),
						array('name'=>'Opera', 'hidden_name'=>'opera', 'logo_path'=>'app_icone_opera_24x24_path'),
						array('name'=>'Safari', 'hidden_name'=>'safari', 'logo_path'=>'app_icone_safari_24x24_path')) as $v) {
			$stmt->execute($v);
		}
	}


    public function down()
    {
        $this->dropTable('ei_browser_type');
        $this->dropTable('ei_device');
        $this->dropTable('ei_device_driver');
        $this->dropTable('ei_device_type');
        $this->dropTable('ei_device_user');
        $this->dropTable('ei_device_user_visibility');
        $this->dropTable('ei_driver_browser');
        $this->dropTable('ei_driver_type');
        $this->removeColumn('ei_execution_stack', 'device_id');
        $this->removeColumn('ei_execution_stack', 'driver_id');
        $this->removeColumn('ei_execution_stack', 'browser_id');
    }
}