<?php
/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version4 extends Doctrine_Migration_Base
{
    public function up()
    {
        $this->addColumn('ei_execution_stack', 'expected_date', 'timestamp', '25', array(
             'notnull' => '',
             'format' => 'yyyy/MM/dd hh:mm:ss',
             ));
    }

    public function down()
    {
        $this->removeColumn('ei_execution_stack', 'expected_date');
    }
}