<?php

/**
 * This class has been auto-generated by the Doctrine ORM Framework
 */
class Version6 extends Doctrine_Migration_Base {

    public function up() {
        /* Gestions des sujets ayant les mêmes packages . */
        $conn = Doctrine_Manager::connection();
        try {
            $conn->beginTransaction();
            //        -- Suppression des paramètre imgPath et imgNoticePath     
            $conn->execute('delete  from ei_profile_param where name in (select param_id from ei_project_param where  name ="imgPath" or name="imgNoticePath")');
            //Suppression des variables globales imgPath et imgNoticePath
            $conn->execute('delete  from ei_project_param where   name ="imgPath" or name="imgNoticePath" ');

			//        -- Mise à jour des notices coté compose
            $str = '<p><img data-mce-src="#{KFT_SCREENSHOT_SERVER}?id=${img}" alt="" src="#{KFT_SCREENSHOT_SERVER}?id=${img}"></p>';
            $stmt = $conn->prepare('update ei_version_notice set result=:new_value where result like   "%#{imgNoticePath}%"');
            $stmt->execute(array('new_value' => $str));

            $conn->commit();
        } catch (Exception $e) {
            $conn->rollback();
            throw $e;
        }
    }

    public function down() {
        
    }

}
