all: 
  stylesheets:    [eidelivery/eigeneric.css,eidelivery/eidelivery.css]
  javascripts:    [eidelivery/eidelivery.js]
  has_layout:     true
  layout:         layout
  
newSuccess: 
  stylesheets:    [eidelivery/newDelivery.css]